DATA.questions.push(...[
{"id":"MS1","topic":"Subtraction","difficulty":"easy","q":"What is the number from which another number is subtracted called?","choices":["Minuend","Subtrahend","Difference","Addend"],"answer":0,"explain":"The minuend is the number from which another number is subtracted.","source":"Reference Card #6"},
{"id":"MS2","topic":"Subtraction","difficulty":"easy","q":"What is the answer in a subtraction problem called?","choices":["Product","Difference or remainder","Sum","Addend"],"answer":1,"explain":"The answer in subtraction is the difference or remainder.","source":"Reference Card #6"},
{"id":"MS3","topic":"Subtraction","difficulty":"medium","q":"Compute 98,267 − 46,035.","choices":["42,232","52,232","52,332","144,302"],"answer":1,"explain":"98,267 − 46,035 = 52,232.","source":"Reference Card #6"},
{"id":"MS4","topic":"Subtraction","difficulty":"medium","q":"How can you check 98,267 − 46,035 = 52,232?","choices":["Add 52,232 + 46,035","Subtract 52,232 − 46,035","Add 98,267 + 46,035","Divide 98,267 by 52,232"],"answer":0,"explain":"Adding the difference and subtrahend should give the minuend: 52,232 + 46,035 = 98,267.","source":"Reference Card #6"},
{"id":"MS5","topic":"Subtraction","difficulty":"medium","q":"Subtract 6.875 − 2.3. Type the exact difference.","type":"text","answerText":["4.575"],"explain":"Write 2.3 as 2.300 and subtract: 6.875 − 2.300 = 4.575.","source":"Subtraction of Decimals"},
{"id":"MS6","topic":"Subtraction","difficulty":"challenge","q":"Subtract 5.1 − 2.543. Type the exact difference.","type":"text","answerText":["2.557"],"explain":"Write 5.1 as 5.100, then 5.100 − 2.543 = 2.557.","source":"Subtraction of Decimals"},
{"id":"MS7","topic":"Subtraction","difficulty":"medium","q":"Estimate 5,189 − 3,672 by rounding each number to its greatest place value first.","choices":["1,000","2,000","3,000","9,000"],"answer":0,"explain":"5,189 rounds to 5,000 and 3,672 rounds to 4,000, so the estimated difference is 1,000.","source":"Estimating Difference"},
{"id":"MS8","topic":"Subtraction","difficulty":"easy","q":"Which clue phrase most strongly suggests subtraction?","choices":["altogether","put together","how much change","in all"],"answer":2,"explain":"How much change commonly asks for the amount left after subtracting a cost from money paid.","source":"Subtraction clue words"},
{"id":"MS9","topic":"Subtraction","difficulty":"medium","q":"When subtracting decimals with different numbers of decimal places, what should you do first?","choices":["Ignore the decimal points","Line up decimal points and add ending zeros if needed","Move every decimal point two places","Round both numbers to whole numbers"],"answer":1,"explain":"Decimal points should be aligned in one column; ending zeros can make the decimal places match.","source":"Subtraction of Decimals"}
]);