DATA.questions.push(...[
{"id":"TA1","topic":"Triangle Angles","difficulty":"easy","q":"What is the sum of the three interior angles of any triangle?","choices":["90°","120°","180°","360°"],"answer":2,"explain":"The interior angles of every triangle add up to 180°.","source":"Triangle angle-sum reference"},
{"id":"TA2","topic":"Triangle Angles","difficulty":"easy","q":"A triangle has angles 30° and 30°. What is the third angle? Type the number of degrees.","type":"text","answerText":["120","120°"],"explain":"180° − (30° + 30°) = 120°.","source":"Triangle angle-sum example"},
{"id":"TA3","topic":"Triangle Angles","difficulty":"medium","q":"A triangle has angles 50° and 60°. What is the third angle? Type the number of degrees.","type":"text","answerText":["70","70°"],"explain":"180° − (50° + 60°) = 70°.","source":"Parallel triangle-angle practice"},
{"id":"TA4","topic":"Triangle Angles","difficulty":"medium","q":"A right triangle has one angle of 90° and another angle of 35°. What is the third angle?","type":"text","answerText":["55","55°"],"explain":"180° − (90° + 35°) = 55°.","source":"Parallel triangle-angle practice"},
{"id":"TA5","topic":"Triangle Angles","difficulty":"easy","q":"A triangle has two angles of 45° each. What is the third angle?","type":"text","answerText":["90","90°"],"explain":"180° − 45° − 45° = 90°.","source":"Parallel triangle-angle practice"},
{"id":"TA6","topic":"Triangle Angles","difficulty":"medium","q":"A triangle has angles 100° and 30°. What is the third angle?","type":"text","answerText":["50","50°"],"explain":"180° − (100° + 30°) = 50°.","source":"Parallel triangle-angle practice"},
{"id":"TA7","topic":"Triangle Angles","difficulty":"medium","q":"A triangle has angles 70° and 65°. What is the third angle?","type":"text","answerText":["45","45°"],"explain":"180° − (70° + 65°) = 45°.","source":"Parallel triangle-angle practice"},
{"id":"TA8","topic":"Triangle Angles","difficulty":"challenge","q":"An equilateral triangle has three equal angles. How many degrees is each angle?","choices":["45°","60°","90°","120°"],"answer":1,"explain":"The three equal angles total 180°, so each is 180° ÷ 3 = 60°.","source":"Equilateral triangle + angle-sum rule"}
]);