const S="Rocio",D=DATA,LS="cp3_rocio_math";document.title=S+"'s Math Reviewer";subjectTitle.textContent=D.icon+" "+S+"'s Math Adventure!";subjectSub.textContent="Hi, "+S+"! "+D.subtitle;
const esc=s=>String(s).replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x])),dk=()=>{let d=new Date;return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")},sh=(a)=>[...a].sort(()=>Math.random()-.5);
function hist(){try{return JSON.parse(localStorage.getItem(LS+"_history"))||[]}catch{return[]}}function save(h){localStorage.setItem(LS+"_history",JSON.stringify(h.slice(-50)))}function reviewer(){reviewerHost.innerHTML=D.reviewer.map((x,i)=>`<article class="card"><div class="cardhead">${x.icon} ${i+1}. ${x.title}</div><div class="cardbody">${x.html}</div></article>`).join("")}
function set(q){let a=[];for(const [t,n] of Object.entries(q)){a.push(...sh(D.questions.filter(x=>x.topic===t)).slice(0,n))}return sh(a)}function daily(){let r=Math.abs([...dk()].reduce((a,c)=>a*31+c.charCodeAt(0),7));return [...set(D.dailyQuotas)].sort((a,b)=>((a.id.charCodeAt(2)+r)%17)-((b.id.charCodeAt(2)+r)%17))}function practice(){return set(D.practiceQuotas)}function mistakes(){let ids=[];try{ids=JSON.parse(localStorage.getItem(LS+"_misses"))||[]}catch{}let m=new Map(D.questions.map(q=>[q.id,q]));return ids.map(x=>m.get(x)).filter(Boolean)}
let st=null;function frame(host,mode,qs){host.innerHTML=`<div class="quiz"><div class="quiztop"><div class="status"><span id="${mode}P"></span><span id="${mode}S"></span></div><div class="progress"><div class="bar" id="${mode}B"></div></div></div><div class="qbody" id="${mode}Q"></div><div class="feedback" id="${mode}F"></div><div class="qactions"><button class="btn secondary" id="${mode}R">↻ Restart</button><button class="btn primary" id="${mode}N" disabled>Next ➜</button></div></div>`;st={host,mode,qs,i:0,score:0,recs:[],lock:false};document.getElementById(mode+"R").onclick=()=>start(mode);document.getElementById(mode+"N").onclick=next;render()}
function start(mode){let qs,host;if(mode==="daily"){qs=daily();host=dailyHost}else if(mode==="practice"){qs=practice();host=practiceHost}else{qs=mistakes();host=practiceHost;if(!qs.length){host.innerHTML='<div class="empty">🌟 No stored mistakes yet. Finish a quiz first.</div>';return}}frame(host,mode,qs)}
function render(){let q=st.qs[st.i],m=st.mode;st.lock=false;document.getElementById(m+"P").textContent=`Question ${st.i+1} of ${st.qs.length}`;document.getElementById(m+"S").textContent=`Score: ${st.score}`;document.getElementById(m+"B").style.width=(st.i/st.qs.length*100)+"%";let h=`<span class="topic">${esc(q.topic)}</span><span class="difficulty">${q.difficulty}</span><div class="question">${q.q}</div>`;if(q.type==="text")h+=`<div class="textrow"><input id="${m}I"><button class="btn primary" id="${m}C">Check</button></div>`;else h+='<div class="answers">'+q.choices.map((c,i)=>`<button class="ans" data-i="${i}">${String.fromCharCode(65+i)}. ${esc(c)}</button>`).join("")+"</div>";document.getElementById(m+"Q").innerHTML=h;let f=document.getElementById(m+"F");f.className="feedback";f.innerHTML="";document.getElementById(m+"N").disabled=true;if(q.type==="text"){document.getElementById(m+"C").onclick=check;document.getElementById(m+"I").onkeydown=e=>e.key==="Enter"&&check()}else document.querySelectorAll(`#${m}Q .ans`).forEach(b=>b.onclick=()=>choose(+b.dataset.i))}
function choose(i){if(st.lock)return;st.lock=true;let q=st.qs[st.i],ok=i===q.answer,bs=st.host.querySelectorAll(".ans");bs.forEach((b,j)=>{b.disabled=true;if(j===q.answer)b.classList.add("correct");if(j===i&&j!==q.answer)b.classList.add("wrong")});finish(ok,q.choices[i],q.choices[q.answer])}function norm(v){return String(v).toLowerCase().replace(/,/g,"").trim()}function check(){if(st.lock)return;let q=st.qs[st.i],v=document.getElementById(st.mode+"I").value;if(!v.trim())return;st.lock=true;let a=(Array.isArray(q.answerText)?q.answerText:[q.answerText]);finish(a.map(norm).includes(norm(v)),v,a[0])}
function finish(ok,y,a){let q=st.qs[st.i];if(ok)st.score++;st.recs.push({id:q.id,topic:q.topic,q:q.q,correct:ok,your:y,answer:a});let f=document.getElementById(st.mode+"F");f.className="feedback "+(ok?"good":"bad");f.textContent=(ok?"✅ Correct! ":"💡 Nice try. ")+q.explain;document.getElementById(st.mode+"S").textContent="Score: "+st.score;document.getElementById(st.mode+"N").disabled=false}
function next(){if(!st.lock)return;if(++st.i<st.qs.length)render();else done()}function done(){let p=Math.round(st.score/st.qs.length*100),miss=st.recs.filter(x=>!x.correct).map(x=>x.id),h=hist(),bt={};st.recs.forEach(r=>{bt[r.topic]??={right:0,total:0};bt[r.topic].total++;if(r.correct)bt[r.topic].right++});localStorage.setItem(LS+"_misses",JSON.stringify(miss));h.push({date:dk(),mode:st.mode,score:st.score,total:st.qs.length,pct:p,byTopic:bt});save(h);st.host.innerHTML=`<div class="quiz"><div class="result"><h2>🎉 Finished!</h2><div class="score">${st.score}/${st.qs.length}</div><h2>${p}%</h2><button class="btn primary" onclick="start('${st.mode}')">Try Again</button></div></div>`;results()}
function view(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));if(id==="results")results()}function results(){let h=hist();if(!h.length){resultsHost.innerHTML='<div class="empty">No Math results yet.</div>';return}let a={};h.forEach(x=>Object.entries(x.byTopic||{}).forEach(([t,s])=>{a[t]??={right:0,total:0};a[t].right+=s.right;a[t].total+=s.total}));resultsHost.innerHTML='<table class="history"><tr><th>Date</th><th>Mode</th><th>Score</th></tr>'+h.slice(-8).reverse().map(x=>`<tr><td>${x.date}</td><td>${x.mode}</td><td>${x.score}/${x.total} (${x.pct}%)</td></tr>`).join("")+"</table>"+Object.entries(a).map(([t,s])=>{let p=Math.round(s.right/s.total*100);return `<p><strong>${t}</strong> ${p}%</p><div class="meter"><span style="width:${p}%"></span></div>`}).join("")}
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>view(b.dataset.view));practiceStart.onclick=()=>start("practice");mistakeStart.onclick=()=>start("mistakes");dailyStart.onclick=()=>start("daily");todayText.textContent=new Date().toLocaleDateString(undefined,{weekday:"long",year:"numeric",month:"long",day:"numeric"});reviewer();results();
