DATA.questions.push(...[
{"id":"PF1","topic":"Plane Figures & Polygons","difficulty":"easy","q":"Which best describes a plane figure?","choices":["A flat two-dimensional figure","A solid with length, width, and height","A figure that must have six faces","A figure with only curved surfaces"],"answer":0,"explain":"A plane figure is flat or two-dimensional.","source":"Reference Card #23"},
{"id":"PF2","topic":"Plane Figures & Polygons","difficulty":"easy","q":"What is a polygon bounded by?","choices":["Straight line segments","Only curved lines","Two circular bases","A curved surface only"],"answer":0,"explain":"Polygons are plane figures bounded by straight line segments.","source":"Reference Card #23"},
{"id":"PF3","topic":"Plane Figures & Polygons","difficulty":"easy","q":"Which is a simple closed curve figure rather than a polygon?","choices":["Triangle","Rectangle","Circle","Pentagon"],"answer":2,"explain":"A circle is bounded by a closed curved line, not straight line segments.","source":"Reference Card #23"},
{"id":"PF4","topic":"Plane Figures & Polygons","difficulty":"medium","q":"What makes a polygon regular?","choices":["All sides and all angles are equal","Only two sides are equal","It has at least one curved side","It has exactly four sides"],"answer":0,"explain":"A regular polygon has equal sides and equal angles.","source":"Reference Card #23"},
{"id":"PF5","topic":"Plane Figures & Polygons","difficulty":"easy","q":"Which is a regular polygon?","choices":["Square","Non-square rectangle","Typical rhombus with unequal angles","Common irregular quadrilateral"],"answer":0,"explain":"A square has four equal sides and four equal angles.","source":"Reference Card #23"},
{"id":"PF6","topic":"Plane Figures & Polygons","difficulty":"medium","q":"Why is a non-square rectangle not a regular polygon?","choices":["Its sides are not all equal","It has no angles","It is not closed","It has curved sides"],"answer":0,"explain":"A rectangle has equal angles, but unless it is a square, all four sides are not equal.","source":"Reference Card #23"},
{"id":"PF7","topic":"Plane Figures & Polygons","difficulty":"medium","q":"Which triangle is a regular polygon?","choices":["Equilateral triangle","Scalene triangle","Right scalene triangle","Obtuse scalene triangle"],"answer":0,"explain":"An equilateral triangle has three equal sides and three equal angles.","source":"Reference Card #23"},
{"id":"PF8","topic":"Plane Figures & Polygons","difficulty":"easy","q":"Which figure is NOT a polygon?","choices":["Pentagon","Square","Oval","Triangle"],"answer":2,"explain":"An oval is bounded by a curved line, so it is not a polygon.","source":"Reference Card #23"}
]);