DATA.questions.push(...[
{"id":"TT1","topic":"Triangle Types & Parts","difficulty":"easy","q":"A triangle has two congruent sides and one right angle. What type is it?","choices":["Right isosceles","Right scalene","Obtuse isosceles","Equilateral"],"answer":0,"explain":"Two congruent sides make it isosceles, and a 90° angle makes it right.","source":"Reference Card #25"},
{"id":"TT2","topic":"Triangle Types & Parts","difficulty":"easy","q":"A triangle has no congruent sides and one right angle. What type is it?","choices":["Right scalene","Right isosceles","Acute scalene","Obtuse scalene"],"answer":0,"explain":"No congruent sides means scalene; one 90° angle means right.","source":"Reference Card #25"},
{"id":"TT3","topic":"Triangle Types & Parts","difficulty":"medium","q":"A triangle has two congruent sides and one obtuse angle. What type is it?","choices":["Obtuse isosceles","Acute isosceles","Right isosceles","Obtuse scalene"],"answer":0,"explain":"Two congruent sides make it isosceles and the obtuse angle determines the angle type.","source":"Reference Card #25"},
{"id":"TT4","topic":"Triangle Types & Parts","difficulty":"medium","q":"A triangle has no congruent sides and one obtuse angle. What type is it?","choices":["Obtuse scalene","Obtuse isosceles","Acute scalene","Right scalene"],"answer":0,"explain":"No congruent sides means scalene; the obtuse angle makes it obtuse.","source":"Reference Card #25"},
{"id":"TT5","topic":"Triangle Types & Parts","difficulty":"medium","q":"A triangle has exactly two congruent sides and all three angles are acute. What type is it?","choices":["Acute isosceles","Acute scalene","Right isosceles","Equilateral only"],"answer":0,"explain":"Exactly two congruent sides make it isosceles in this classification, and three acute angles make it acute.","source":"Reference Card #25"},
{"id":"TT6","topic":"Triangle Types & Parts","difficulty":"medium","q":"A triangle has no congruent sides and all three angles are acute. What type is it?","choices":["Acute scalene","Acute isosceles","Obtuse scalene","Right scalene"],"answer":0,"explain":"No congruent sides means scalene and all acute angles make it an acute triangle.","source":"Reference Card #25"},
{"id":"TT7","topic":"Triangle Types & Parts","difficulty":"easy","q":"Which triangle has three congruent sides and three congruent angles?","choices":["Equilateral","Scalene","Right scalene","Obtuse isosceles"],"answer":0,"explain":"An equilateral triangle has three congruent sides and three congruent angles.","source":"Reference Card #25"},
{"id":"TT8","topic":"Triangle Types & Parts","difficulty":"easy","q":"In a right triangle, what is the side opposite the right angle called?","choices":["Hypotenuse","Median","Base angle","Bisector"],"answer":0,"explain":"The hypotenuse lies opposite the right angle and is the longest side.","source":"Parts of a Triangle application"},
{"id":"TT9","topic":"Triangle Types & Parts","difficulty":"easy","q":"What are the other two sides of a right triangle called?","choices":["Legs","Bases","Medians","Axes"],"answer":0,"explain":"The two sides other than the hypotenuse are called legs.","source":"Parts of a Triangle application"},
{"id":"TT10","topic":"Triangle Types & Parts","difficulty":"medium","q":"What does a median of a triangle connect?","choices":["A vertex to the midpoint of the opposite side","Two vertices","A vertex perpendicularly to any point on the opposite side","The midpoints of two sides only"],"answer":0,"explain":"A median joins a vertex to the midpoint of the opposite side.","source":"Reference Card #26"},
{"id":"TT11","topic":"Triangle Types & Parts","difficulty":"medium","q":"What best describes an altitude of a triangle?","choices":["A perpendicular segment from a vertex to the opposite side or its extension","A segment joining two midpoints","Any side used as a base","The total of all side lengths"],"answer":0,"explain":"An altitude is perpendicular to the opposite side or its extension.","source":"Reference Card #26"},
{"id":"TT12","topic":"Triangle Types & Parts","difficulty":"medium","q":"What does an angle bisector do?","choices":["Divides an angle into two equal angles","Cuts a side into three equal parts","Makes every triangle isosceles","Adds two angles together"],"answer":0,"explain":"An angle bisector divides one angle into two congruent angles.","source":"Reference Card #26"},
{"id":"TT13","topic":"Triangle Types & Parts","difficulty":"challenge","q":"What is the axis (perpendicular bisector) of a side?","choices":["A line perpendicular to the side through its midpoint","A line from a vertex to any point on the base","The longest side","The sum of all three sides"],"answer":0,"explain":"The perpendicular bisector crosses the side at its midpoint at a right angle.","source":"Reference Card #26"},
{"id":"TT14","topic":"Triangle Types & Parts","difficulty":"easy","q":"What is the perimeter of a triangle?","choices":["The total length of its three sides","The space inside the triangle","The largest angle","The height from a vertex"],"answer":0,"explain":"Perimeter is the sum of the lengths of all sides.","source":"Reference Card #26"},
{"id":"TT15","topic":"Triangle Types & Parts","difficulty":"easy","q":"What is a vertex of a triangle?","choices":["A point where two sides meet","The inside surface","A line through the midpoint of a side","The total side length"],"answer":0,"explain":"A vertex is a corner point where two sides meet.","source":"Reference Card #26"},
{"id":"TT16","topic":"Triangle Types & Parts","difficulty":"medium","q":"In an isosceles triangle, what is the angle opposite the base called?","choices":["Vertex angle","Right angle","Exterior angle","Straight angle"],"answer":0,"explain":"The angle opposite the base is the vertex angle.","source":"Parts of a Triangle application"},
{"id":"TT17","topic":"Triangle Types & Parts","difficulty":"medium","q":"In an isosceles triangle, what are the two congruent sides called?","choices":["Legs","Bases","Hypotenuses","Medians"],"answer":0,"explain":"The two congruent sides are called the legs; the third side is the base.","source":"Parts of a Triangle application"}
,
{"id":"TT18","topic":"Triangle Types & Parts","difficulty":"easy","q":"What is the surface of a triangle?","choices":["The region of the plane bounded by its sides","The total length of its sides","The longest side","A point where two sides meet"],"answer":0,"explain":"The surface is the region of the plane enclosed by the triangle's sides.","source":"Reference Card #26"},
{"id":"TT19","topic":"Triangle Types & Parts","difficulty":"easy","q":"What is an angle of a triangle formed by?","choices":["Two consecutive sides meeting at a vertex","All three sides added together","A midpoint and a base only","Two parallel faces"],"answer":0,"explain":"An angle is formed where two consecutive sides meet at a vertex.","source":"Reference Card #26"}
]);