DATA.questions.push(...[
{"id":"MA6","topic":"Addition","difficulty":"easy","q":"Which property is shown by 8 + 6 = 6 + 8?","choices":["Commutative Property","Associative Property","Identity Property","Subtraction Property"],"answer":0,"explain":"The addends change order, but the sum stays the same.","source":"Reference Card #5 continuation"},
{"id":"MA7","topic":"Addition","difficulty":"medium","q":"Which property is shown by (2 + 3) + 4 = 2 + (3 + 4)?","choices":["Identity Property","Associative Property","Commutative Property","Inverse Property"],"answer":1,"explain":"The grouping changes, but the order of the addends stays the same.","source":"Reference Card #5 continuation"},
{"id":"MA8","topic":"Addition","difficulty":"easy","q":"Which property is shown by 15 + 0 = 15?","choices":["Associative Property","Commutative Property","Identity Property","Distributive Property"],"answer":2,"explain":"Zero is the identity element for addition.","source":"Reference Card #5 continuation"},
{"id":"MA9","topic":"Addition","difficulty":"medium","q":"Estimate 3,579 + 1,426 by rounding each number to its greatest place value first.","choices":["4,000","5,000","5,500","6,000"],"answer":1,"explain":"3,579 rounds to 4,000 and 1,426 rounds to 1,000. Their estimated sum is 5,000.","source":"Reference Card #5 continuation"},
{"id":"MA10","topic":"Addition","difficulty":"medium","q":"Add 1.47 + 3.5. Type the exact sum.","type":"text","answerText":["4.97"],"explain":"Write 3.5 as 3.50 and align decimal points: 1.47 + 3.50 = 4.97.","source":"Addition of Decimal Numbers"},
{"id":"MA11","topic":"Addition","difficulty":"challenge","q":"Add 108.80 + 45.50 + 49.25. Type the exact sum.","type":"text","answerText":["203.55"],"explain":"Keeping the decimal points aligned gives 203.55.","source":"Addition of Decimal Numbers"},
{"id":"MA12","topic":"Addition","difficulty":"medium","q":"A chicken costs ₱150 and pork costs ₱175. How much is the total cost? Type the amount as a number.","type":"text","answerText":["325","325.00"],"explain":"150 + 175 = 325.","source":"Addition word problem"},
{"id":"MA13","topic":"Addition","difficulty":"medium","q":"What is the exact sum of 3,579 + 1,426?","type":"text","answerText":["5005","5,005"],"explain":"3,579 + 1,426 = 5,005.","source":"Estimating Sum example"}
]);