DATA.questions.push(...[
{"id":"SF1","topic":"Space Figures","difficulty":"easy","q":"A space figure is three-dimensional. Which measurements does it have?","choices":["Length, width, and height","Length only","Length and width only","Angle and perimeter only"],"answer":0,"explain":"A three-dimensional figure has length, width, and height.","source":"Reference Card #24"},
{"id":"SF2","topic":"Space Figures","difficulty":"easy","q":"What is a polyhedron?","choices":["A solid with flat faces","A flat plane figure","A solid with only curved surfaces","A circle with a center"],"answer":0,"explain":"A polyhedron is a solid bounded by plane or flat faces.","source":"Reference Card #24"},
{"id":"SF3","topic":"Space Figures","difficulty":"easy","q":"What special feature does a prism have?","choices":["Two parallel congruent bases","One base and one vertex only","No flat faces","Exactly one circular base"],"answer":0,"explain":"A prism has two parallel congruent faces called bases.","source":"Reference Card #24"},
{"id":"SF4","topic":"Space Figures","difficulty":"medium","q":"What special feature does a pyramid have?","choices":["One base with triangular lateral faces meeting at a common vertex","Two circular bases","No vertices","Two parallel congruent bases"],"answer":0,"explain":"A pyramid has one base and triangular lateral faces that meet at a common vertex.","source":"Reference Card #24"},
{"id":"SF5","topic":"Space Figures","difficulty":"medium","q":"How many vertices does a cube have?","choices":["4","6","8","12"],"answer":2,"explain":"A cube has 8 vertices.","source":"Reference Card #24 continuation"},
{"id":"SF6","topic":"Space Figures","difficulty":"medium","q":"A rectangular prism has how many edges?","choices":["6","8","9","12"],"answer":3,"explain":"A rectangular prism has 12 edges.","source":"Reference Card #24 continuation"},
{"id":"SF7","topic":"Space Figures","difficulty":"medium","q":"A triangular prism has how many vertices?","choices":["4","5","6","8"],"answer":2,"explain":"A triangular prism has 6 vertices.","source":"Reference Card #24 continuation"},
{"id":"SF8","topic":"Space Figures","difficulty":"medium","q":"A triangular pyramid has how many edges?","choices":["4","5","6","8"],"answer":2,"explain":"A triangular pyramid has 6 edges.","source":"Reference Card #24 continuation"},
{"id":"SF9","topic":"Space Figures","difficulty":"medium","q":"A square pyramid has how many vertices?","choices":["4","5","6","8"],"answer":1,"explain":"A square pyramid has 4 base vertices plus the top vertex, for 5 total.","source":"Reference Card #24 continuation"},
{"id":"SF10","topic":"Space Figures","difficulty":"easy","q":"Which solid has two equal, parallel circular bases?","choices":["Cylinder","Cone","Sphere","Hemisphere"],"answer":0,"explain":"A cylinder has two equal and parallel circular bases.","source":"Reference Card #24 continuation"},
{"id":"SF11","topic":"Space Figures","difficulty":"easy","q":"Which solid has one circular base and a single vertex?","choices":["Cylinder","Cone","Sphere","Cube"],"answer":1,"explain":"A cone has one circular base and narrows to a single vertex.","source":"Reference Card #24 continuation"},
{"id":"SF12","topic":"Space Figures","difficulty":"easy","q":"Which solid has no flat face?","choices":["Sphere","Hemisphere","Cylinder","Cone"],"answer":0,"explain":"A sphere has no flat face; its surface is entirely curved.","source":"Reference Card #24 continuation"},
{"id":"SF13","topic":"Space Figures","difficulty":"easy","q":"How many flat faces does a hemisphere have?","choices":["0","1","2","3"],"answer":1,"explain":"A hemisphere has one flat circular face.","source":"Reference Card #24 continuation"},
{"id":"SF14","topic":"Space Figures","difficulty":"medium","q":"What is an edge of a space figure?","choices":["A line segment where two faces meet","A flat region that makes up the solid","The point where several edges meet","The face on which the solid rests"],"answer":0,"explain":"An edge is a line segment where two faces meet or intersect.","source":"Reference Card #24"}
]);